export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS';
export const GET_ALL_TYPES = 'GET_ALL_TYPES';
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER';
export const SET_SORTER = 'SET_SORTER';
export const PAGINATION = 'PAGINATION';
export const LOADING = 'LOADING';
